import type { Config } from '../config.js';
import { badRequest, conflict, notFound } from '../errors.js';
import type { SesControlPlane } from '../providers/control-plane.js';
import type { Store } from '../store/types.js';
import type { DnsRecord, Domain, Id } from '../types.js';
import { newId } from '../util/ids.js';
import { audit } from './audit.js';
import type { DnsResolver } from './dns.js';

const DOMAIN_RE = /^(?!-)[a-z0-9-]{1,63}(\.[a-z0-9-]{1,63})+$/;

export class DomainService {
  constructor(
    private readonly store: Store,
    private readonly config: Config,
    private readonly dns: DnsResolver,
    private readonly ses: SesControlPlane,
  ) {}

  async add(accountId: Id, input: string): Promise<Domain> {
    const domain = input.trim().toLowerCase().replace(/\.$/, '');
    if (!DOMAIN_RE.test(domain)) throw badRequest('That is not a valid domain name.', 'domain');
    if (await this.store.findDomain(accountId, domain)) {
      throw conflict(`Domain ${domain} is already registered on this account.`);
    }

    const account = await this.store.getAccount(accountId);
    if (!account) throw notFound('Account');

    const mailFromSubdomain = `mail.${domain}`;
    const configSetName = `cs-${domain.replace(/[^a-z0-9]/g, '-')}`;

    // Provision in SES first: the DKIM selectors in the records below are
    // generated by AWS, not by us. Inventing them locally would produce records
    // that can never verify.
    await this.ses.createConfigurationSet(configSetName);
    const identity = await this.ses.createIdentity(domain, configSetName);
    await this.ses.setMailFrom(domain, mailFromSubdomain);
    await this.ses.associateWithTenant(account.tenantName, this.ses.arnFor('identity', domain));
    await this.ses.associateWithTenant(
      account.tenantName,
      this.ses.arnFor('configuration-set', configSetName),
    );

    const records: DnsRecord[] = [
      ...identity.dkimTokens.map<DnsRecord>((token) => ({
        type: 'CNAME',
        name: `${token}._domainkey.${domain}`,
        value: this.ses.dkimTarget(token),
        purpose: 'dkim',
        status: 'pending',
      })),
      {
        type: 'MX',
        name: mailFromSubdomain,
        value: `feedback-smtp.${this.config.awsRegion}.amazonses.com`,
        priority: 10,
        purpose: 'mail_from',
        status: 'pending',
      },
      {
        type: 'TXT',
        name: mailFromSubdomain,
        value: 'v=spf1 include:amazonses.com ~all',
        purpose: 'mail_from',
        status: 'pending',
      },
      {
        type: 'TXT',
        name: domain,
        value: 'v=spf1 include:amazonses.com ~all',
        purpose: 'spf',
        status: 'pending',
      },
    ];

    const created = await this.store.createDomain({
      id: newId('dom'),
      accountId,
      domain,
      mailFromSubdomain,
      configSetName,
      status: 'pending',
      records,
      warnings: [],
      verifiedAt: null,
      createdAt: new Date().toISOString(),
    });
    await audit(this.store, {
      accountId,
      actor: 'api',
      action: 'domain.added',
      target: created.id,
      metadata: { domain },
    });
    return created;
  }

  async get(accountId: Id, id: Id): Promise<Domain> {
    const domain = await this.store.getDomain(id);
    if (!domain || domain.accountId !== accountId) throw notFound('Domain');
    return domain;
  }

  async list(accountId: Id): Promise<Domain[]> {
    return this.store.listDomains(accountId);
  }

  async remove(accountId: Id, id: Id): Promise<void> {
    const domain = await this.get(accountId, id);
    // FR-2.6: drop the SES identity before forgetting the record, so a failure
    // here leaves something to retry rather than an orphaned AWS resource.
    await this.ses.deleteIdentity(domain.domain);
    await this.store.deleteDomain(id);
    await audit(this.store, {
      accountId,
      actor: 'api',
      action: 'domain.removed',
      target: id,
      metadata: { domain: domain.domain },
    });
  }

  /**
   * Re-checks every published record and re-runs the deliverability
   * diagnostics. A domain is verified once all three DKIM CNAMEs and the
   * MAIL FROM MX resolve (DR-1, DR-2).
   */
  async verify(accountId: Id, id: Id): Promise<Domain> {
    const domain = await this.get(accountId, id);
    const records: DnsRecord[] = [];

    for (const record of domain.records) {
      records.push({ ...record, status: (await this.check(record)) ? 'verified' : 'pending' });
    }

    const required = records.filter((r) => r.purpose === 'dkim' || (r.purpose === 'mail_from' && r.type === 'MX'));
    const dnsReady = required.every((r) => r.status === 'verified');

    // DNS resolving is necessary but not sufficient: SES has to have seen the
    // records and marked the identity verified before it will sign anything.
    const identity = await this.ses.getIdentityStatus(domain.domain);
    const verified = dnsReady && (this.ses.name === 'local' || identity.verifiedForSending);

    const warnings = await this.diagnose(domain, records);
    if (dnsReady && !verified) {
      warnings.push(
        `DNS is published but SES reports DKIM status ${identity.dkimStatus}. ` +
          'Verification can take up to 72 hours after the records resolve.',
      );
    }

    const updated = await this.store.updateDomain(id, {
      records,
      warnings,
      status: verified ? 'verified' : 'pending',
      verifiedAt: verified ? domain.verifiedAt ?? new Date().toISOString() : null,
    });
    if (updated.status !== domain.status) {
      await audit(this.store, {
        accountId,
        actor: 'api',
        action: `domain.${updated.status}`,
        target: id,
        metadata: { domain: domain.domain, warnings },
      });
    }
    return updated;
  }

  private async check(record: DnsRecord): Promise<boolean> {
    if (record.type === 'CNAME') {
      const values = await this.dns.resolveCname(record.name);
      return values.some((value) => value.toLowerCase().replace(/\.$/, '') === record.value.toLowerCase());
    }
    if (record.type === 'MX') {
      const values = await this.dns.resolveMx(record.name);
      return values.some((mx) => mx.exchange.toLowerCase().replace(/\.$/, '') === record.value.toLowerCase());
    }
    const values = await this.dns.resolveTxt(record.name);
    return values.some((value) => value.trim() === record.value);
  }

  /**
   * The three misconfigurations that silently destroy delivery (FR-2.4, DR-3):
   * a strict DMARC policy with nothing aligned to satisfy it, more than one SPF
   * record, and a MAIL FROM subdomain with no MX.
   */
  private async diagnose(domain: Domain, records: DnsRecord[]): Promise<string[]> {
    const warnings: string[] = [];

    const dmarc = (await this.dns.resolveTxt(`_dmarc.${domain.domain}`)).find((v) =>
      v.toLowerCase().startsWith('v=dmarc1'),
    );
    const policy = dmarc?.match(/\bp\s*=\s*(none|quarantine|reject)/i)?.[1]?.toLowerCase();
    const dkimReady = records.filter((r) => r.purpose === 'dkim').every((r) => r.status === 'verified');
    const mailFromReady = records
      .filter((r) => r.purpose === 'mail_from')
      .every((r) => r.status === 'verified');

    if (policy && policy !== 'none' && !dkimReady && !mailFromReady) {
      warnings.push(
        `DMARC policy is p=${policy} but neither DKIM nor an aligned MAIL FROM is in place yet. ` +
          'Mail sent now will be quarantined or rejected. Publish the DKIM records first.',
      );
    }

    const spfRecords = (await this.dns.resolveTxt(domain.domain)).filter((v) =>
      v.toLowerCase().startsWith('v=spf1'),
    );
    if (spfRecords.length > 1) {
      warnings.push(
        `${spfRecords.length} SPF records found on ${domain.domain}. RFC 7208 permits exactly one; ` +
          'merge them into a single record or SPF fails outright.',
      );
    }

    const mx = await this.dns.resolveMx(domain.mailFromSubdomain);
    if (!mx.length) {
      warnings.push(
        `No MX record on ${domain.mailFromSubdomain}. Without it the custom MAIL FROM does not work, ` +
          'so SPF cannot align for DMARC.',
      );
    }

    return warnings;
  }
}
